# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Schedule1.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Schedule1.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0fSchedule1.proto\"1\n\x03\x44\x61y\x12\x0c\n\x04name\x18\x03 \x02(\t\x12\x0e\n\x06parity\x18\x01 \x02(\t\x12\x0c\n\x04pair\x18\x02 \x02(\t')
)




_DAY = _descriptor.Descriptor(
  name='Day',
  full_name='Day',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Day.name', index=0,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='parity', full_name='Day.parity', index=1,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pair', full_name='Day.pair', index=2,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=68,
)

DESCRIPTOR.message_types_by_name['Day'] = _DAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Day = _reflection.GeneratedProtocolMessageType('Day', (_message.Message,), dict(
  DESCRIPTOR = _DAY,
  __module__ = 'Schedule1_pb2'
  # @@protoc_insertion_point(class_scope:Day)
  ))
_sym_db.RegisterMessage(Day)


# @@protoc_insertion_point(module_scope)
